Support startY in makegrid to run function more than once.
grafana/grafonnet pull request #109
Opened 2023-08-31 17:59 UTC by v-zhuravlev

This small addition allows to run makeGrid more than once or combine generated grid with other panels.

```
            + g.dashboard.withPanels(
                    g.util.grid.makeGrid(
                    [
                        g.panel.row.new("CPU")
                            + g.panel.row.withPanels([
                                g.panel.stat.new("test"),
                                g.panel.stat.new("test"),
                                g.panel.stat.new("test"),
                                g.panel.stat.new("test"),
                                g.panel.stat.new("test"),
                                g.panel.stat.new("test"),
                                g.panel.stat.new("test"),
                                g.panel.stat.new("test"),
                                g.panel.stat.new("test"),
                            ]),
                    ],
                    6, 2, startY=0)
                    +
                    g.util.grid.makeGrid(
                    [
                        g.panel.row.new("CPU")
                            + g.panel.row.withPanels([
                                g.panel.stat.new("test"),
                                g.panel.stat.new("test"),
                                g.panel.stat.new("test"),
                            ]),
                        g.panel.row.new("CPU100")
                            + g.panel.row.withPanels([
                                g.panel.stat.new("test"),
                                g.panel.stat.new("test"),
                                g.panel.stat.new("test"),
                                g.panel.stat.new("test"),
                            ]),
                    ],
                    8, 6, startY=100),
            )
```

Produces:
![image](https://github.com/grafana/grafonnet/assets/14870891/d194a9cf-3fae-4b6a-89a1-36421c464784)

2023-08-31 18:33 UTC, malcolmholmes commented
I wonder if `makeGrid` could store `startY` as a hidden element on `panels[]`. Then you wouldn't need to specify it, each invocation will build on where the last one left off.

2023-08-31 18:36 UTC, v-zhuravlev commented
> I wonder if `makeGrid` could store `startY` as a hidden element on `panels[]`. Then you wouldn't need to specify it, each invocation will build on where the last one left off.

Sounds like some 'magic' :)

2023-09-05 06:44 UTC, Duologic requested changes

2023-09-05 06:44 UTC, Duologic commented on grafonnet-base/util/grid.libsonnet
> +        local y = acc.nexty + startY,
I think setting `startY` needs to happen in the `std.foldl` init, not here.

```diff
         local rows = root.countRows(panelsBeforeRowGroups, panelWidth),
-        nexty: (rows * panelHeight) + rows,
+        nexty: (rows * panelHeight) + rows + startY,

         lastRowPanelHeight: 0,  // starts without a row panel

         // Create a grid for the panels that come before the rowGroups
-        panels: root.makePanelGrid(panelsBeforeRowGroups, panelWidth, panelHeight, 0),
+        panels: root.makePanelGrid(panelsBeforeRowGroups, panelWidth, panelHeight, startY),
       }
     ).panels,
 }
```

2023-09-05 19:56 UTC, Duologic approved these changes

2023-09-05 19:56 UTC, merged